use_frameworks!
source 'https://github.com/ZkmlEasycarOrganization/ZkmlRemotePodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'ZKMLToolsModule_Example' do
  pod 'ZKMLToolsModule', :path => '../'

  target 'ZKMLToolsModule_Tests' do
    inherit! :search_paths
  end
end
