use_frameworks!

platform :ios, '8.0'

target 'ZKMLToolsModule_Example' do
  pod 'ZKMLToolsModule', :path => '../'

  target 'ZKMLToolsModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
